### PR TITLE
Update foundryOracle.sh

### PR DESCRIPTION
**Pull request by dsakura**
updated node and added the hostname on options.json

### CODE REVIEW

**Comment by aco-rt** [comment]
Let's update to v20 of nodejs, and no need to add the update commands for pm2, as this script is for new installation. 

Having a separate update sequence that stops pm2, updates and then starts it again is a bit more clean. I think this can be done manually with a few commands using

https://foundryvtt.wiki/en/setup/linux-installation#updating-nodejs

**Comment by dsakura** [comment]
Its true, but whenever I do the initial install of pm2, it already tells to update, so I added it, but it works fine as a separate command really. Adding this entire node update part and clean reinstall/update as a batch command would be nice too.
Sorry for any difficulties with terms, English is not my native language.

**Comment by aco-rt** [comment]
After thinking for a bit, I think keeping most folks in nodejs v18 may be better, as its the LTS (long term support) version. 

Yes, I can write a script for the update to v11.

Thanks for the input.

**Comment by dsakura** [comment]
Perfect! Thanks

**Comment by dsakura** [comment]
Hello! Do you test the install script? 
I changed it a little, but especially I added comments in my language, but I ended up with an error that I haven't identified well yet, related to pm2, and also not finding the config.json file to change. Curious that the first test was successful and 3 in a row I found an error. One I was able to revert by reinstalling pm2, the other not.
[](https://raw.githubusercontent.com/dsakura/Foundry-VTT-Oracle/main/foundryVM2.sh)

Sorry if bother you and many thanks
WhatsApp Image 2023-08-07 at 13 43 57

**Comment by aco-rt** [comment]
During my update to v11, I used this script to install v10 on a new VM, and did the upgrade. So yes, i tested it. Not sure what could cause a problem on your end. You said you changed it. So not sure how I can help. I will take a look at your script if you have it on GitHub and let you know. 

But, this script works well for me, i will wait for a few more reports before I make any alterations.

**Comment by dsakura** [comment]
I appreciate it. I had posted the script in the previous message, there must have been an error. Thanks again
https://raw.githubusercontent.com/dsakura/Foundry-VTT-Oracle/main/foundryVM2.sh

**Pull request merged**
